### ISSUE TITLE
Fix navbar overlap

### ISSUE THREAD

**Issue by J3RN** [CWDG/design-circle#33]
This is happening on my computer:
![screen shot 2015-03-25 at 12 17 54 pm](https://cloud.githubusercontent.com/assets/2058614/6829287/fbea3d08-d2e8-11e4-9d25-28c82938e391.png)

The "Archive" link is being covered by the navbar

**Comment by d30xy** [comment]
I'm thinking the easiest fix would be to put an empty, fixed-size container behind the nav bar within `<div class="content-wrapper">` and after `<div class="content">` so that all of the content is pushed up above the nav bar.

I don't know if putting the nav bar and content in the same plane (opposed to the nav bar floating on top of the content like it is now) will play nicely with scrollify

**Comment by J3RN** [comment]
Well, here's the interesting part: The content is just too big.

If we made the `div` around it smaller, the content would simply flow out of it and remain the same size (_thanks for nothing, CSS_). That is, unless we added `overflow: auto` which would produce scrollbars (_eww_) or `overflow: hidden`, which would simply pretend the extra content does not exist, and hide it.

**Comment by mrogman** [comment]
Yeah, you're right. We could make the make the font size in those divs dynamic and relate them to the view port height. That way it should fit nicely into any screen size.

Another option could be to change how the images resize. Right now it seems like they're set to 100% of the width of the column, instead we could relate the size of the image to the height of the container so that the images shrink if the window shrinks vertically. I haven't familiarized myself with the grid layout we have now so I don't know how easy this would be to do.

Or we could just make everything smaller in general. I just feel like there will be way too much whitespace on larger screens.

As for the overflow idea, we could use `overflow: hidden` and have an elipsis in the bottom right corner that indicates that there is more (which would be fine for the blog section because I figure that text will be the first few lines of the blog post itself). Or if we go with the variable font sizes, then this would pretty much be a non-issue.

**Comment by mrogman** [comment]
We could implement something like this if we want to go with dynamic font sizes:

``` javascript
function fontResize() {
    //Set default resolution and font size
    var resolution = 1024;
    var font = 13;

    //Get window width
    var width = $(window).width();

    //Set new font size
    var newFont = font * (width/resolution);
    $('body').css('font-size', newFont);
};
```

[Demo](http://www.dotticontra.org/devel/javascript/jquery_dynamic_font_resize_demo/)

**Comment by J3RN** [comment]
For at least a quick fix, we might trim the blog post preview. That said, we're going to need some idea of what a mobile layout will look like, so we can create transitions between desktop, tablet, and phone views.

Since Allison doesn't seem to be working on the mobile layout, I'll give it a shot.

Somewhat relevantly, if we ditch Scrollify and the idea of the whole snap-to-page thing, this becomes a non-issue

**Comment by mrogman** [comment]
#34 has the quick fix

**Comment by J3RN** [comment]
I think this can be closed for now.
